volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13.10
    env_file: .env 
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:${IMAGE_TAG:-latest}
    env_file: .env
    volumes:
      - static:/app/collected_static/
      - media:/app/media/
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    env_file: .env
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:${IMAGE_TAG:-latest}
    volumes:
      - static:/app/static/

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:${IMAGE_TAG:-latest}
    volumes:
          - static:/usr/share/nginx/html/static/:ro
          - media:/usr/share/nginx/html/media/:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend